name: CI-CD (Build, Tests, Quality, Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-test-quality:
    name: Build + Tests + Quality (Checkstyle/SpotBugs)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build + Tests + Quality
        run: mvn -B clean verify

      # Optionnel: pour garder le jar en artifact
      - name: Upload JAR artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  docker-build-push:
    name: Docker Build + Push
    needs: build-test-quality
    runs-on: ubuntu-latest

    # on push l'image seulement si c'est un push sur main (pas sur PR)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build JAR (skip tests because already done)
        run: mvn -B -DskipTests package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build & push image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/studentevents:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/studentevents:${{ github.sha }}
